### PR TITLE
updated changelog in README for 1.2.0

### PR DESCRIPTION
**Pull request by zkiiito**
You could release this as 1.2.0, I've upgraded the change log in the readme.
Please do so, requiring dev-master is painful :(

### CODE REVIEW

**Comment by miniche** [comment]
Seems good for you @GromNaN and @j0k3r?

**Comment by GromNaN** [comment]
Let's do it.

**Comment by j0k3r** [comment]
:+1:

**Comment by GromNaN** [comment]
Version tagged.
https://github.com/LExpress/sfWebBrowserPlugin/releases/tag/1.2.0

**Comment by j0k3r** [comment]
Changelod added into the tag.

**Comment by miniche** [comment]
Thanks!

**Comment by zkiiito** [comment]
please push an update to packagist too, the tag is not there yet: https://packagist.org/packages/lexpress/sf-web-browser-plugin

**Pull request merged**
